services:
  psql_goworkout:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${GOWORKOUT_DB_DATABASE}
      POSTGRES_USER: ${GOWORKOUT_DB_USERNAME}
      POSTGRES_PASSWORD: ${GOWORKOUT_DB_PASSWORD}
    ports:
      - "${GOWORKOUT_DB_PORT}:5432"
    volumes:
      - psql_volume_goworkout:/var/lib/postgresql/data

  backend_goworkout:
    image: golang:latest
    restart: unless-stopped
  ports:  
    - "${GOWORKOUT_DB_PORT}:8080"

volumes:
  psql_volume_goworkout:
